import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import QueryProvider from './myComponents/QueryProvider';
import Contextprovider from './myComponents/ContextProvider';
import { DarkModeProvider } from './myComponents/darkModeProvider';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "َAdmin Dashboard",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
        <link rel="icon" href="/favicon-admin-blue.ico?v=2" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <DarkModeProvider>
           <Contextprovider>
          <QueryProvider>{children}</QueryProvider>
        </Contextprovider>
        </DarkModeProvider>
       
      </body>
    </html>
  );
}
